{
 "title": "Vault Identity Net",
 "description": "Demo dashboard for Vault Identity Net",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Vault License",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "time:YYYY-MM-DD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vault_core_license_expiration_time_epoch)*1000"
    }
   ]
  },
  {
   "title": "Authentication Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vault_core_handle_login_request_count[5m]))"
    }
   ]
  },
  {
   "title": "Leases",
   "type": "stat",
   "description": "Number of Leases across namespaces",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(vault_expire_num_leases)" }
   ]
  },
  {
   "title": "Vault Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vault_autopilot_node_healthy", "legendFormat": "{{node_id}}" }
   ]
  },
  {
   "title": "Average Login Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vault_core_handle_login_request_sum[5m]) / rate(vault_core_handle_login_request_count[5m]))"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vault_identity_num_entities)"
    }
   ]
  },
  {
   "title": "Identity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Identity Entities Aliases by Method",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without(instance) (vault_identity_entity_alias_count)",
       "legendFormat": "{{auth_method}}"
      }
     ]
    },
    {
     "title": "Entity Count by Namespace",
     "type": "table",
     "gridPos": { "h": 6, "w": 9, "x": 4, "y": 8 },
     "targets": [
      {
       "expr": "sum by (namespace) (vault_identity_entity_count)"
      }
     ]
    }
   ]
  },
  {
   "title": "Audit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Audit Log Request Failures",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(idelta(vault_audit_log_request_failure[5m]))"
      }
     ]
    },
    {
     "title": "Audit Log Requests",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 5, "y": 15 },
     "targets": [
      {
       "expr": "avg(irate(vault_audit_log_request_count[5m]))",
       "legendFormat": "Audit Request"
      },
      {
       "expr": "avg(irate(vault_audit_log_response_count[5m]))",
       "legendFormat": "Audit Response"
      },
      {
       "expr": "avg(irate(vault_core_handle_request_count[5m]))",
       "legendFormat": "Handled by Vault Core"
      }
     ]
    },
    {
     "title": "Audit Log Response Failures",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(idelta(vault_audit_log_response_failure[5m]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raft Performance",
     "type": "timeseries",
     "description": "Performance of Raft Integrated Storage Backend",
     "gridPos": { "h": 8, "w": 13, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "sum(rate(vault_raft_storage_delete_sum[5m]) / rate(vault_raft_storage_delete_count[5m]))",
       "legendFormat": "AVG DEL"
      },
      {
       "expr": "sum(rate(vault_raft_storage_list_sum[5m]) / rate(vault_raft_storage_list_count[5m]))",
       "legendFormat": "AVG LIST"
      },
      {
       "expr": "sum(rate(vault_raft_storage_get_sum[5m]) / rate(vault_raft_storage_get_count[5m]))",
       "legendFormat": "AVG GET"
      },
      {
       "expr": "sum(rate(vault_raft_storage_put_sum[5m]) / rate(vault_raft_storage_put_count[5m]))",
       "legendFormat": "AVG PUT"
      }
     ]
    }
   ]
  }
 ]
}