---

groups:
  testgroup:
    namespaces:
      tenant: {}
      tenant2: {}
      tenant3: {}
    metadata:
      owner: foo@bar.com
      cost_center: FooBar
  testgroup2:
    namespaces:
      tenant: {}
    metadata:
      owner: foo2@bar.com
